# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
  - repository: Implementation # The name used to reference this repository in the checkout step
    type: github
    endpoint: milanatedufied
    name: milanatedufied/Ed-Fi-ODS-Implementation
  - repository: ODS
    type: github
    endpoint: milanatedufied
    name: milanatedufied/Ed-Fi-ODS

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: ODS
- checkout: Implementation

- task: NuGetToolInstaller@1

- task: PowerShell@2
  inputs:
    targetType: inline
    workingDirectory: Ed-Fi-ODS-Implementation
    script: |
      Import-Module Ed-Fi-ODS-Implementation\Initialize-PowershellForDevelopment.ps1
      initdev -NoDeploy -NoRebuild

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: 'Ed-Fi-ODS\nuget.config'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription(434bef23-7f24-49ef-848b-66c95f1cb749)'
    appType: 'webApp'
    WebAppName: 'edufied-edfi-api'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'